urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'piman.views.home', name='home'),
    # url(r'^piman/', include('piman.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/login','django.contrib.auth.views.login'),
    url(r'^accounts/logout','django.contrib.auth.views.logout'),
    url(r'^accounts/register','pis.views.register'), 
    url(r'^accounts/profile','pis.views.profile'),
    url(r'^pis/students_block', 'pis.views.students_block'),
    url(r'^pis/teaching_block', 'pis.views.teaching_block'),
    url(r'^pis/grants_block', 'pis.views.grants_block'),
    url(r'^pis/publications_block', 'pis.views.publications_block'),

    url(r'grants', 'grants.views.manage'),
    url(r'publications','publications.views.manage'),
    url(r'students', 'students.views.manage'),
    url(r'courses', 'courses.views.manage'),
    url(r'projects', 'projects.views.manage'),


    # CRUD 
    # Student projects 
    url(r'^student/create', 'students.views.student_create'),
    url(r'^study_level/create', 'students.views.study_level_create'),
    url(r'^project/create', 'students.views.project_create'),
    url(r'^project_pi/create', 'students.views.project_pi_create'),
    url(r'^milestone/create', 'students.views.milestone_create'),

    url(r'^student/(?P<student_id>\d+)/edit$', 'students.views.student_edit'),
    url(r'^study_level/(?P<study_level_id>\d+)/edit$', 'students.views.study_level_edit'),
    url(r'^project/(?P<project_id>\d+)/edit$', 'students.views.project_edit'),
    url(r'^project_pi/(?P<project_pi_id>\d+)/edit$', 'students.views.project_pi_edit'),
    url(r'^milestone/(?P<milestone_id>\d+)/edit$', 'students.views.milestone_edit'),
 

)

students/models.py
from django.db import models
from taggit.managers import TaggableManager

class StudyLevel(models.Model):
   name        = models.CharField(max_length=20)
   description = models.TextField(blank=True)

   def __unicode__(self):
      return self.name


class Student(models.Model):
   name        = models.CharField(max_length=100)
   description = models.TextField(blank=True)
   start_year  = models.ForeignKey('acad_year.AcademicYear', related_name="student_start_year")
   end_year    = models.ForeignKey('acad_year.AcademicYear', related_name="student_end_year")
   level       = models.ForeignKey(StudyLevel)

   def __unicode__(self):
      return self.name


class Project(models.Model):
   name         = models.CharField(max_length=255)
   description  = models.TextField(blank=True)
   supervisors  = models.ManyToManyField('pis.PI', through='ProjectPI', related_name='projects')
   start_year   = models.ForeignKey('acad_year.AcademicYear', related_name="project_start_year")
   end_year     = models.ForeignKey('acad_year.AcademicYear', related_name="project_end_year")
   students     = models.ManyToManyField(Student, blank=True, related_name="projects")
   notes        = models.TextField(blank=True)

   tags         = TaggableManager(blank=True)

   def __unicode__(self):
      return self.name

class Milestone(models.Model):
   project        = models.ForeignKey(Project)
   name           = models.CharField(max_length=100)
   description    = models.TextField()
   notes          = models.TextField(blank=True)
   due_date       = models.DateField()
   complete_date  = models.DateField(blank=True, null=True)

   tags           = TaggableManager(blank=True)

   def __unicode__(self):
      return self.name
   

class ProjectPI(models.Model):
   project     = models.ForeignKey(Project)
   pi          = models.ForeignKey('pis.PI')
   percentage  = models.IntegerField()
   notes       = models.TextField(blank=True)
   
   def __unicode__(self):
      return self.supervisor.user.name 

students/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import render_to_response, get_object_or_404
from django.core.exceptions import *
from django.forms import ModelForm
from datetime import datetime
from students.models import *
from functions import *
import json

class StudyLevelForm(ModelForm):
  class Meta:
    model = StudyLevel

def study_level_create(request):
  if request.method == 'POST':
    form = StudyLevelForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('/study_level/create')
  else:
    form = StudyLevelForm()
  
  t = loader.get_template('students/study_level_create.html')
  c = RequestContext(request, {'form' : form } )
  return HttpResponse(t.render(c))

def study_level_edit(request, study_level_id):
  if request.method == 'POST':
    form = StudyLevelForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('/study_level/edit')
  else:
    study_level = get_object_or_404(StudyLevel, pk=study_level_id)
    form = StudyLevelForm(instance=study_level)

  t = loader.get_template('students/study_level_edit.html')
  c = RequestContext(request, {'form' : form, 'id' : study_level.id } )
  return HttpResponse(t.render(c))


class StudentForm(ModelForm):
  class Meta:
    model = Student

def student_create(request):
  if request.method == 'POST': 
    form = StudentForm(request.POST) 
    if form.is_valid(): 
      form.save()
      return HttpResponseRedirect('/student/create') 
  else:
    form = StudentForm() 

  t = loader.get_template('students/student_create.html')
  c = RequestContext(request, {'form' : form } )
  return HttpResponse(t.render(c))

def student_edit(request, student_id):
  if request.method == 'POST':
    form = StudentForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('students/student_edit.html')
  else:
    student = get_object_or_404(Student, pk=student_id)
    form = StudentForm(instance=student)

  t = loader.get_template('students/student_edit.html')
  c = RequestContext(request, {'form' : form, 'id' : student.id } )
  return HttpResponse(t.render(c))



class ProjectForm(ModelForm):
  class Meta:
    model = Project

def project_create(request):
  if request.method == 'POST':
    form = ProjectForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('/project/create')
  else:
    form = ProjectForm()

  t = loader.get_template('students/project_create.html')
  c = RequestContext(request, { 'form'  : form,
                                 'user' : request.user } )
  return HttpResponse(t.render(c))

@ajax_login_required
def project_edit(request, project_id):

  if request.method == 'POST':
    form = ProjectForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('students/project_edit.html')
  else:
    project = get_object_or_404(Project, pk=project_id)
    form = ProjectForm(instance=project)

  t = loader.get_template('students/project_edit.html')
  c = RequestContext(request, {'form' : form, 'id' : project.id } )
  html = t.render(c)
 
  # return the html as a json object in data.html
  # possibly for debugging this should just return the html if a get req.
  response =  HttpResponse(json.dumps({'html' : html}), mimetype=u'application/json')
  return response
  


class MilestoneForm(ModelForm):
  class Meta:
    model = Milestone

def milestone_create(request):
  if request.method == 'POST':
    form = MilestoneForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('/milestone/create')
  else:
    form = MilestoneForm()

  t = loader.get_template('students/milestone_create.html')
  c = RequestContext(request, {'form' : form } )
  return HttpResponse(t.render(c))

def milestone_edit(request, milestone_id):
  if request.method == 'POST':
    form = MilestoneForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('students/milestone_edit.html')
  else:
    milestone = get_object_or_404(Milestone, pk=milestone_id)
    form = MilestoneForm(instance=milestone)

  t = loader.get_template('students/milestone_edit.html')
  c = RequestContext(request, {'form' : form, 'id': milestone.id } )
  return HttpResponse(t.render(c))




class ProjectPIForm(ModelForm):
  class Meta:
    model = ProjectPI


def project_pi_create(request):
  if request.method == 'POST':
    form = ProjectPIForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('/project_pi/create')
  else:
    form = ProjectPIForm()

  t = loader.get_template('students/project_pi_create.html')
  c = RequestContext(request, {'form' : form } )
  return HttpResponse(t.render(c))


def project_pi_edit(request, project_pi_id):
  if request.method == 'POST':
    form = ProjectPIForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('students/project_pi_edit.html')
  else:
    project_pi = get_object_or_404(ProjectPI, pk=project_pi_id)
    form = ProjectPIForm(instance=project_pi)

  t = loader.get_template('students/project_pi_edit.html')
  c = RequestContext(request, {'form' : form, 'id' : project_pi.id} )
  return HttpResponse(t.render(c))

templates/students/milestone_create.html
<form action="/milestone/create" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

templates/students/milestone_edit.html
<form action="/milestone/{{id}}/edit" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

templates/students/project_create.html
<form action="/project/create" method="post">{% csrf_token %}
<!-- This isn't enough - need to add the create links for the many to many students
     relationship. Also need to set the PI to the current user. If the current user
     is a manager, they should be able to select the PI and create a new one.
 -->
{{ form.non_field_errors }}

  <div class="fieldWrapper">
    {{ form.name.errors }}
    <label for="id_name">Name:</label>
    {{ form.name }}
  </div>

  <div class="fieldWrapper">
    {{ form.description.errors }}
    <label for="id_description">Description:</label>
    {{ form.description }}
  </div>

  <!-- Should these just be dates? Or does everyone have the same deadlines
       in an academic year?
   -->
  <div class="fieldWrapper">
    {{ form.start_year.errors }}
    <label for="id_start_year">Start Year:</label>
    {{ form.start_year }}
  </div>

  <div class="fieldWrapper">
    {{ form.end_year.errors }}
    <label for="id_end_year">End Year:</label>
    {{ form.end_year }}
  </div>

  <div class="fieldWrapper">
    {{ form.notes.errors }}
    <label for="id_notes">Notes:</label>
    {{ form.notes }}
  </div> 


  <!-- Mangers should be able to select and create supervisors -->
  <div class="fieldWrapper">
    {{ form.supervisors.errors }}
    <label for="id_supervisors">Supervisors:</label>
    {{ form.supervisors }}
  <div> 
  
  <!-- PIs should be able to select and create students -->
  <div class="fieldWrapper">
    {{ form.students.errors }}
    <label for="id_students">Students:</label>
    {{ form.students }}
  </div>

  <div class="fieldWrapper">
    {{ form.tags.errors }}
    <label for="id_tags">Tags:</label>
    {{ form.tags }}
  </div>

<input type="submit" value="Submit" />
</form>

templates/students/project_edit.html
<form action="" name="project_edit_form" id="project_edit_form">{% csrf_token %}
<img src="/static/images/close.png" class="close_button" onclick="piman_clear_hide('overlay');" />

    <h1 class="form_title">Edit Project:</h1>

    {{ form.non_field_errors }}
   
    <span class="id hidden">{{id}}</span>

    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="id_name">Name:</label>
        {{ form.name }}
    </div>

    <div class="fieldWrapper">
        {{ form.description.errors }}
        <label for="id_description">Description:</label>
        {{ form.description }}
    </div>

    <div class="fieldWrapper">
        {{ form.start_year.errors }}
        <label for="id_start_year">Start Year:</label>
        {{ form.start_year }}
    </div>

    <div class="fieldWrapper">
        {{ form.end_year.errors }}
        <label for="id_end_year">End Year:</label>
        {{ form.end_year }}
    </div>

    <div class="fieldWrapper">
        {{ form.notes.errors }}
        <label for="id_notes">Notes:</label>
        {{ form.notes }}
    </div>

    <div class="fieldWrapper">
        {{ form.students.errors }}
        <label for="id_students">Students:</label>
        {{ form.students }}
    </div>

    <div class="fieldWrapper">
        {{ form.tags.errors }}
        <label for="id_tags">Tags:</label>
        {{ form.tags }}
    </div>

    <button>Not a submit button</button>
   
    <div class="form_buttons">
        <button class="submit_button" onclick="piman_project_edit_submit({{id}})">Submit</button>
        <!--button class="submit_button" onclick="piman_submit('project_edit_form','/project/edit/{{id}}'); return(false)">Submit</button-->
        <!--button  class="submit_button"  onclick="piman_submit('project_edit_form','/project/edit/{{id}}', function(){piman_clear_hide('overlay'); piman_fill_show('student_block','/pis/students_block')}); return false;">Submit</button-->
    </div>
</form>

templates/students/project_pi_create.html
<form action="/project_pi/create" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

templates/students/project_pi_edit.html
<form action="/project_pi/{{id}}/edit" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

templates/students/student_create.html
<form action="/student/create" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

templates/students/student_edit.html
<form action="/student/{{id}}/edit" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

templates/students/study_level_create.html
<form action="/study_level/create" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

templates/students/study_level_edit.html
<form action="/study_level/{{id}}/edit" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>